# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size : [288, 180], mode : outbound }
                background: { size : [290, 182], position : center, color : '#d3d3d3' }

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
